name: Backend Workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'fastapi/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
    S3_BUCKET: elasticbeanstalk-us-east-1-086227530319
    APPLICATION_NAME: fitcal-app
    APP_ENV: fitcal-app-env

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Zip FastAPI Files
      run: |
        cd fastapi
        zip -r ${{ github.run_id }}.zip application.py database.py models.py requirements.txt Procfile

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fastapi-zip
        path: fastapi/${{ github.run_id }}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v5
      with:
        name: fastapi-zip

    - name: AWS Configure
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: arn:aws:iam::086227530319:role/tf-role
        aws-region: us-east-1
        role-session-name: GitHubActions

    - name: Upload to S3
      run: |
        aws s3 cp ${{ github.run_id }}.zip s3://${{ env.S3_BUCKET }}/${{ github.run_id }}.zip

    - name: Create New Application Version
      run: |  
        aws elasticbeanstalk create-application-version --application-name ${{ env.APPLICATION_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket=${{ env.S3_BUCKET }},S3Key=${{ github.run_id }}.zip

    - name: Update Elastic Beanstalk Environment
      run: |
        aws elasticbeanstalk update-environment --environment-name ${{ env.APP_ENV }} --version-label ${{ github.run_id }}